import type { ProcessingOptions } from "./types";

export const DEFAULT_SPRITE_PROCESSING_OPTIONS: ProcessingOptions = {
  keepEvery: 2,
  outputScale: 100,
  canvasMode: "auto",
  reducePx: 0,
  chromaEnabled: true,
  matteMode: "chroma",
  keyMode: "auto",
  manualKeyHex: "#00ff00",
  threshold: 42,
  softness: 8,
  despillStrength: 0.6,
  haloPixels: 1,
  foregroundProtectEnabled: false,
  foregroundProtectHex: "#2f8f3a",
  foregroundProtectTolerance: 34,
  foregroundProtectStrength: 1,
  corridorkeyScreen: "auto",
  lumaBlack: 0,
  lumaWhite: 85,
  lumaGamma: 0.55,
  lumaStrength: 1.7,
  batchGreenToBlack: false,
  batchGreenDesaturate: false,
  batchSemiTransparentToBlack: false,
  batchSemiTransparentToOpaque: false,
};
